name: rappel_priere2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0
  intl: ^0.20.2
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ressources/
    - assets/ressources/background.png
    - assets/ressources/logo.png

